name: Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Build Linux"
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Build Windows"
